/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FarmerRole;

import Business.EcoSystem;

import Business.Enterprise.Enterprise;
import Business.Enterprise.USFDEnterprise;
import Business.Produce.Produce;
import Business.Organization.FarmerOrganization;
import Business.Organization.Organization;
import Business.Organization.StaffOrganization;
import Business.Produce.ProduceDirectory;
import Business.RawMaterialReview.RawMaterialReview;
import Business.RawMaterialReview.RawMaterialReviewDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProduceRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class FarmerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private FarmerOrganization farmerOrganization;
    private USFDEnterprise enterprise;
    private ProduceDirectory produceDirectory;
    private RawMaterialReviewDirectory rmrDirectory;
    private ButtonGroup qualitybg = new ButtonGroup();
    private ButtonGroup shelfbg = new ButtonGroup();
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */

    public FarmerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise ,EcoSystem business,ProduceDirectory produceDirectory,RawMaterialReviewDirectory rmrDirectory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.farmerOrganization = (FarmerOrganization)organization;
        this.enterprise = (USFDEnterprise)enterprise;
        this.produceDirectory = produceDirectory;
        this.rmrDirectory = rmrDirectory;
        System.out.println("farmer panel produce directory"+ produceDirectory);
        populateTable();
        populateRequestRMTable();
        populateCropTable();
        populatermCombo();
         qualitygroupbutton();
         shelfgroupbutton();
        
  
    }
     private void qualitygroupbutton() {
        qualitybg.add(qexRadioButton);
        qualitybg.add(qvgRadioButton);
        qualitybg.add(qgRadioButton);
        qualitybg.add(qaRadioButton);
        qualitybg.add(qpRadioButton);
    }
    
     private void shelfgroupbutton() {
        shelfbg.add(sleRadioButton);
        shelfbg.add(svgRadioButton);
        shelfbg.add(sgRadioButton);
        shelfbg.add(saRadioButton);
        shelfbg.add(spRadioButton);
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : farmerOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            row[4] = request.getCropQty();
            model.addRow(row);
            
        }
    }
    
    public void populateCropTable(){
        
       DefaultTableModel model = (DefaultTableModel)produceTable.getModel();
        
        model.setRowCount(0);
        
        for(Produce produce : produceDirectory.getProduceList()){
            Object[] row = new Object[4];
            row[0] = produce;
            row[1] = produce.getCropQuantity();
            row[2] = produce.getCropPrice();
            //row[3] = userAccount.getUsername();
            row[3] = produce.getFarmerName();
            model.addRow(row);
        }
    }

        void populateRequestRMTable() {
        DefaultTableModel model = (DefaultTableModel) requestRMjTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request.getMessage();
            row[1] = request.getSender();
            row[2] = request.getReceiver();
            String result = ((ProduceRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
            row[4] = request.getRawMaterialQty();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        produceTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cropNameTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        requestRMjTable = new javax.swing.JTable();
        requestTestJButton = new javax.swing.JButton();
        weatherButton = new javax.swing.JButton();
        addCropButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qexRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        sleRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        additionalreviewsTextArea = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();
        svgRadioButton = new javax.swing.JRadioButton();
        qvgRadioButton = new javax.swing.JRadioButton();
        qgRadioButton = new javax.swing.JRadioButton();
        sgRadioButton = new javax.swing.JRadioButton();
        saRadioButton = new javax.swing.JRadioButton();
        qaRadioButton = new javax.swing.JRadioButton();
        qpRadioButton = new javax.swing.JRadioButton();
        spRadioButton = new javax.swing.JRadioButton();
        reviewSupplyButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Crop Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 58, 440, 96));

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 215, -1, -1));

        processJButton.setText("Process");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 215, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 26, -1, -1));

        produceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Crop Name", "Quantity", "Price", "Farmer"
            }
        ));
        jScrollPane2.setViewportView(produceTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, 170));

        jLabel1.setText("Crop Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, -1, -1));

        jLabel3.setText("Price");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, -1, -1));
        add(cropNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 200, -1));
        add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 200, -1));
        add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 670, 200, -1));

        requestRMjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Raw material Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(requestRMjTable);
        if (requestRMjTable.getColumnModel().getColumnCount() > 0) {
            requestRMjTable.getColumnModel().getColumn(0).setResizable(false);
            requestRMjTable.getColumnModel().getColumn(1).setResizable(false);
            requestRMjTable.getColumnModel().getColumn(2).setResizable(false);
            requestRMjTable.getColumnModel().getColumn(3).setResizable(false);
            requestRMjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 620, 90));

        requestTestJButton.setText("Request Raw Material");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        weatherButton.setText("Weather Information");
        weatherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weatherButtonActionPerformed(evt);
            }
        });
        add(weatherButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        addCropButton.setText("Add Crop");
        addCropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCropButtonActionPerformed(evt);
            }
        });
        add(addCropButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, -1));

        jLabel4.setText("Review Supply");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, -1, 10));

        jLabel5.setText("Supply Quality");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, -1, -1));

        qexRadioButton.setText("Excellent");
        qexRadioButton.setEnabled(false);
        add(qexRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, -1, -1));

        jLabel6.setText("Supply Shelf Life");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, -1, -1));

        sleRadioButton.setText("Excellent");
        sleRadioButton.setEnabled(false);
        add(sleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, -1, -1));

        jLabel7.setText("Additional Reviews");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 620, -1, -1));

        additionalreviewsTextArea.setColumns(20);
        additionalreviewsTextArea.setRows(5);
        additionalreviewsTextArea.setEnabled(false);
        jScrollPane5.setViewportView(additionalreviewsTextArea);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, -1, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 740, -1, -1));

        svgRadioButton.setText("Very Good");
        svgRadioButton.setEnabled(false);
        add(svgRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, -1, -1));

        qvgRadioButton.setText("Very Good");
        qvgRadioButton.setEnabled(false);
        qvgRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qvgRadioButtonActionPerformed(evt);
            }
        });
        add(qvgRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, -1, -1));

        qgRadioButton.setText("Good");
        qgRadioButton.setEnabled(false);
        add(qgRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 510, -1, -1));

        sgRadioButton.setText("Good");
        sgRadioButton.setEnabled(false);
        add(sgRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 550, -1, -1));

        saRadioButton.setText("Average");
        saRadioButton.setEnabled(false);
        add(saRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 550, -1, -1));

        qaRadioButton.setText("Average");
        qaRadioButton.setEnabled(false);
        add(qaRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 510, -1, -1));

        qpRadioButton.setText("Poor");
        qpRadioButton.setEnabled(false);
        add(qpRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 480, -1, -1));

        spRadioButton.setText("Poor");
        spRadioButton.setEnabled(false);
        add(spRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 590, -1, -1));

        reviewSupplyButton.setText("Review Supply");
        reviewSupplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewSupplyButtonActionPerformed(evt);
            }
        });
        add(reviewSupplyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 333, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();
       // String selectedRM = (String)rmComboBox.getSelectedItem();

        if (selectedRow < 0){
            return;
        }
        
        
        /*int i =0;
        for(int j=0; j<requestRMjTable.getRowCount();j++){
            String valueRMTable = requestRMjTable.getModel().getValueAt(j, i).toString();
            if(!(selectedRM.equalsIgnoreCase(valueRMTable))){
                continue;
            }                         
            else {
                
                break;
                
            }

        }

        JOptionPane.showMessageDialog(null, "can not assign, request for raw material");
  */
        WorkRequest request = (WorkRequest)workRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Pending");
        String cropName = workRequestJTable.getModel().getValueAt(selectedRow, 0).toString();
        int cropQty = Integer.parseInt((String.valueOf(workRequestJTable.getModel().getValueAt(selectedRow, 4))));
        populateTable();
        if(cropName.equalsIgnoreCase("rice")) if(cropName.equalsIgnoreCase("tomato")){
            JOptionPane.showMessageDialog(null, "The amount of pesticides required for rice of quality pest A is" + (cropQty*2) + 
                    "The amount of pesticides required for rice of quality pest B is" + (cropQty/2)+ "The amount of pesticides required for rice of quality pest A is" +(cropQty*1.5));
        }
        
        
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        
        int selectedRow = workRequestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        ProduceRequest request = (ProduceRequest)workRequestJTable.getValueAt(selectedRow, 0);
     
        request.setStatus("Processing");
        
        ProcessProduceRequestJPanel processWorkRequestJPanel = new ProcessProduceRequestJPanel(userProcessContainer, request);
        userProcessContainer.add("ProcessProduceJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_processJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestProduceJPanel", new RequestRawMaterialJPanel(userProcessContainer, userAccount, enterprise,produceDirectory));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void weatherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weatherButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("WeatherInformationJPanel", new WeatherInformationJPanel (userProcessContainer));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_weatherButtonActionPerformed

    private void addCropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCropButtonActionPerformed
        // TODO add your handling code here:
        try 
        {
        if(cropNameTextField.getText().equals("") || quantityTextField.getText().equals("") || priceTextField.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please fill all the details");
         else if (checkIfCropExists(cropNameTextField.getText()))
        {
            Produce produce =  produceDirectory.addProduce();
            produce.setCropName(cropNameTextField.getText());
            produce.setCropPrice(Double.parseDouble(priceTextField.getText()));
            produce.setCropQuantity(Integer.parseInt(quantityTextField.getText()));
            produce.setFarmerName(userAccount.getUsername());
            populateCropTable();
        }
        else {
             String tempName = null;   
             int cropQty = Integer.parseInt(quantityTextField.getText());
             int i = 0;
             String cropName = cropNameTextField.getText();
             for(int j = 0; j <produceTable.getRowCount(); j++){
             tempName = produceTable.getModel().getValueAt(j, i).toString();
             
             if(tempName.equalsIgnoreCase(cropName)){
                i++;
               
                cropQty = Integer.parseInt((String.valueOf(produceTable.getModel().getValueAt(j, i)))) + cropQty;
                 //System.out.println("New qunty" +cropQty);
                
                for (Produce prod : produceDirectory.getProduceList())
                {
                    if (prod.getCropName().equalsIgnoreCase(cropName))
                     prod.setCropQuantity(cropQty);
                }
                break;
            }
        }
             populateCropTable();
            }
        }
        catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"Please enter a number in Quantity  and price");
            }
    }//GEN-LAST:event_addCropButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = requestRMjTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        String status = requestRMjTable.getValueAt(selectedRow, 3).toString();
        String supplyName = requestRMjTable.getValueAt(selectedRow, 0).toString();
        String supplierName = requestRMjTable.getValueAt(selectedRow, 2).toString();

        //ProduceReview pr = prDirectory.addProduceReview();
        if(status.equalsIgnoreCase("done")){
            RawMaterialReview rmr = rmrDirectory.addRawMaterialReview();
            rmr.setSupplyName(supplyName);
           rmr.setSupplierName(supplierName);

            String quality = null;
            if(qexRadioButton.isSelected())
            quality = "Excellent";
            else if (qvgRadioButton.isSelected())
            quality = "Very Good";
            else if (qgRadioButton.isSelected())
            quality = "Good";
            else if (qaRadioButton.isSelected())
            quality = "Average";
            else if(qpRadioButton.isSelected())
            quality = "Poor";

            String shelfLife = null;

            if(sleRadioButton.isSelected())
            shelfLife = "Excellent";
            else if (svgRadioButton.isSelected())
            shelfLife = "Very Good";
            else if (sgRadioButton.isSelected())
            shelfLife = "Good";
            else if (saRadioButton.isSelected())
            shelfLife = "Average";
            else if(spRadioButton.isSelected())
            shelfLife = "Poor";

            rmr.setProduceQuality(quality);
            rmr.setProduceShelfLife(shelfLife);
            rmr.setAdditionalReviews(additionalreviewsTextArea.getText());
        }

        qexRadioButton.setEnabled(false);
        qvgRadioButton.setEnabled(false);
        qgRadioButton.setEnabled(false);
        qaRadioButton.setEnabled(false);
        qpRadioButton.setEnabled(false);

        sleRadioButton.setEnabled(false);
        svgRadioButton.setEnabled(false);
        sgRadioButton.setEnabled(false);
        saRadioButton.setEnabled(false);
        spRadioButton.setEnabled(false);

        additionalreviewsTextArea.setEnabled(false);

        qualitybg.clearSelection();
        shelfbg.clearSelection();

        additionalreviewsTextArea.setText(" ");
    }//GEN-LAST:event_submitButtonActionPerformed

    private void qvgRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qvgRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qvgRadioButtonActionPerformed

    private void reviewSupplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewSupplyButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = requestRMjTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
       
       String status = requestRMjTable.getValueAt(selectedRow, 3).toString();
       
       if(status.equalsIgnoreCase("done")){

            
           
            qexRadioButton.setEnabled(true);
            qvgRadioButton.setEnabled(true);
            qgRadioButton.setEnabled(true);
            qaRadioButton.setEnabled(true);
            qpRadioButton.setEnabled(true);

            sleRadioButton.setEnabled(true);
            svgRadioButton.setEnabled(true);
            sgRadioButton.setEnabled(true);
            saRadioButton.setEnabled(true);
            spRadioButton.setEnabled(true);
            
            additionalreviewsTextArea.setEnabled(true);
        
       }
       else{
           JOptionPane.showMessageDialog(null, "Request not fulfilled");
       }
        
    }//GEN-LAST:event_reviewSupplyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCropButton;
    private javax.swing.JTextArea additionalreviewsTextArea;
    private javax.swing.JButton assignJButton;
    private javax.swing.JTextField cropNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton processJButton;
    private javax.swing.JTable produceTable;
    private javax.swing.JRadioButton qaRadioButton;
    private javax.swing.JRadioButton qexRadioButton;
    private javax.swing.JRadioButton qgRadioButton;
    private javax.swing.JRadioButton qpRadioButton;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JRadioButton qvgRadioButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable requestRMjTable;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton reviewSupplyButton;
    private javax.swing.JRadioButton saRadioButton;
    private javax.swing.JRadioButton sgRadioButton;
    private javax.swing.JRadioButton sleRadioButton;
    private javax.swing.JRadioButton spRadioButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JRadioButton svgRadioButton;
    private javax.swing.JButton weatherButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

    private boolean checkIfCropExists(String text) {
         boolean flag = true;
        for (Produce produce: produceDirectory.getProduceList()){
            String temp = produce.getCropName();
            if(temp == null)
            {   
                break;
            }
            else if (temp.equalsIgnoreCase(text))
            {
                flag = false;
                break;
            }
                else
                flag = true;
        } 
        
        return flag;
    }

    private void populatermCombo() {
        /*rmComboBox.addItem("Pest A");
        rmComboBox.addItem("Pest B");
        rmComboBox.addItem("Pest C");
*/

    }

  
}